kind: NamespaceConfig
apiVersion: redhatcop.redhat.io/v1alpha1
metadata:
  name: test-namespaceconfig-dev
spec:
  labelSelector:
    matchLabels:
      namespace: important-project-dev
  templates:
    - objectTemplate: |
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: projectdefault
          namespace: {{ .Name }}
        spec:
          hard:
            pods: "4" 
            requests.cpu: "1" 
            requests.memory: 1Gi 
            limits.cpu: "2" 
            limits.memory: 2Gi 
---
kind: NamespaceConfig
apiVersion: redhatcop.redhat.io/v1alpha1
metadata:
  name: test-namespaceconfig-staging
spec:
  labelSelector:
    matchLabels:
      namespace: important-project-staging
  templates:
    - objectTemplate: |
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: projectdefault
          namespace: {{ .Name }}
        spec:
          hard:
            pods: "8" 
            requests.cpu: "2"
            requests.memory: 2Gi 
            limits.cpu: "4" 
            limits.memory: 4Gi
---
kind: NamespaceConfig
apiVersion: redhatcop.redhat.io/v1alpha1
metadata:
  name: test-namespaceconfig-prod
spec:
  labelSelector:
    matchLabels:
      namespace: important-project-prod
  templates:
    - objectTemplate: |
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: projectdefault
          namespace: {{ .Name }}
        spec:
          hard:
            pods: "8" 
            requests.cpu: "2" 
            requests.memory: 2Gi 
            limits.cpu: "4" 
            limits.memory: 4Gi
    - objectTemplate: |
        apiVersion: v1
        kind: LimitRange
        metadata:
          name: projectlimitrange
          namespace: {{ .Name }}
        spec:
          limits:
            - default:
                memory: 512Mi
              defaultRequest:
                memory: 256Mi
              type: Container