apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/namespace-configuration-operator.namespace-configuration-operat: ""
  name: namespace-configuration-operator
  namespace: namespace-configuration-operator
spec:
  channel: alpha
  installPlanApproval: Manual
  name: namespace-configuration-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
